#!/bin/sh

#
# jupyter tool
#
/usr/bin/invoke_app "$@" -t alpsinteract \
                         -C "start_jupyter -T -A @tool -t alpsinteract.ipynb" \
                         -u anaconda-X \
                         -r none \
                         -w headless

